package com.example.afit_gr1

import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.example.afit_gr1.data.database.AppDatabase
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import java.io.IOException
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * Test for verifying Room database migrations.
 * Note: To run this test successfully, Room must be configured to export schemas in build.gradle:
 * javaCompileOptions {
 *     annotationProcessorOptions {
 *         arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
 *     }
 * }
 * And the schemas for previous versions must exist in the schemas folder.
 */
@RunWith(AndroidJUnit4::class)
class DatabaseMigrationTest {

    private val TEST_DB = "migration-test"

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java.canonicalName,
        FrameworkSQLiteOpenHelperFactory()
    )

    // Example migration from version 7 to 8
    val MIGRATION_7_8 = object : Migration(7, 8) {
        override fun migrate(database: SupportSQLiteDatabase) {
            // Assume we added a 'notes' column to the 'plan_table'
            database.execSQL("ALTER TABLE plan_table ADD COLUMN notes TEXT DEFAULT ''")
        }
    }

    @Test
    @Throws(IOException::class)
    fun migrate7To8() {
        // Create database with version 7 schema
        // Note: This requires the 7.json schema file to be generated by Room and placed in the schemas/ directory
        // Uncomment the code below once schemas are exported.
        
        /*
        var db = helper.createDatabase(TEST_DB, 7)
        
        // Insert some data using SQL into version 7
        db.execSQL("INSERT INTO plan_table (id, exercise, calories, repeat_count, selected_days, completed) VALUES (1, 'Squat', 100.0, 10, 'Monday', 0)")
        
        // Prepare for the next version
        db.close()
        
        // Re-open the database with version 8 and provide MIGRATION_7_8 as the migration process
        // MigrationTestHelper will automatically verify the schema matches the 8.json schema
        db = helper.runMigrationsAndValidate(TEST_DB, 8, true, MIGRATION_7_8)
        
        // Query the data to ensure it was preserved and the new column exists
        val cursor = db.query("SELECT * FROM plan_table WHERE id = 1")
        assert(cursor.moveToFirst())
        val notesIndex = cursor.getColumnIndex("notes")
        assert(notesIndex != -1)
        */
    }
}
